Donatsi/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import  static
from . import settings
from .views import homepage, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name="homepage"), #homepage ntar
    path('tentang-kami/', about, name="about"),
    path('donasi/', include("PermohonanDonasi.urls", namespace="permohonan")),
    path('donasi/', include("PemberianDonasi.urls", namespace="pemberian")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

PemberianDonasi/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import daftar_pemberian

app_name = "pemberian"
urlpatterns = [
    path('<id>/beri-donasi', daftar_pemberian, name="daftar_pemberian"),
]

PermohonanDonasi/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import daftar_permohonan, list_permohonan, detail_permohonan

app_name = "permohonan"
urlpatterns = [
    path('', list_permohonan, name="list-permohonan"),
    path('<id>', detail_permohonan, name="detail-permohonan"),
    path('daftar/', daftar_permohonan, name="daftar-permohonan")
]

Comments/models.py
from django.db import models

# Create your models here.

KategoriDonasi/models.py
from django.db import models

# Create your models here.
class Kategori(models.Model):
    nama_kategori = models.CharField(max_length=100)
    key_kategori = models.CharField(max_length=100)
    urgency = models.PositiveIntegerField()
    def __str__(self):
        return self.nama_kategori

PemberianDonasi/models.py
from django.db import models

# Create your models here.
class Pemberian(models.Model):
    donasi = models.ForeignKey("PermohonanDonasi.Permohonan", on_delete=models.CASCADE)
    nama_pemberi = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    nomor_telp = models.CharField(max_length=13)
    jumlah_uang = models.PositiveIntegerField()
    kartu_kredit = models.CharField(max_length=50)

    def __str__(self):
        return self.nama_pemberi

PermohonanDonasi/models.py
from django.db import models
import django.utils.timezone
from KategoriDonasi.models import Kategori

# Create your models here.
class Permohonan(models.Model):
    # KATEGORI = [
    #     ('bencana', 'Bencana'),
    #     ('kesehatan', 'Kesehatan'),
    #     ('kegiatan_sosial', 'Kegiatan sosial'),
    #     ('beasiswa_pendidikan', 'Beasiswa pendidikan'),
    #     ('lainnya', 'Lainnya')
    # ]

    email = models.EmailField(max_length=100)
    nama_pemohon = models.CharField(max_length=100)
    bank = models.CharField(max_length=100)
    rekening = models.CharField(max_length=100)
    nomor_telp = models.CharField(null=True, max_length=13)
    nama_donasi = models.CharField(max_length=100)
    image_donasi = models.ImageField(upload_to="images/", default="images/donatsi.png")
    target_uang = models.PositiveIntegerField()
    uang_terpenuhi = models.PositiveIntegerField(default=0, null=True)
    deadline = models.DateField(auto_now_add = False)

    # pilihan_kategori_alasan = models.CharField(max_length=100, choices=KATEGORI,
    #     default='kegiatan_sosial'
    # )
    kategori_alasan = models.ForeignKey('KategoriDonasi.Kategori', null=True, on_delete=models.CASCADE)
    urgency = models.PositiveIntegerField(default=0, null=True)
    deskripsi_alasan = models.TextField(max_length=500)
    # comments = models.ForeignKey('Comments.Comment', on_delete=models.CASCADE)
    # semua_pemberian = models.ForeignKey('PemberianDonasi.Pemberian', on_delete=models.CASCADE)
    tanggal_pembuatan = models.DateField(default = django.utils.timezone.now)

    def __str__(self):
        return self.nama_donasi
    
    def deskripsi_singkat(self):
        if(len(self.deskripsi_alasan) > 50):
            return self.deskripsi_alasan[:50] + "..."
        return self.deskripsi_alasan

PemberianDonasi/forms.py
from django import forms
from . import models
from django.utils import timezone
from datetime import datetime

class CreatePemberian(forms.ModelForm):
    class Meta:
        model = models.Pemberian
        fields = "__all__"
        exclude = ['donasi']

PermohonanDonasi/forms.py
from django import forms
from . import models
from django.utils import timezone
from datetime import datetime

class DateInput(forms.DateInput):
    input_type = "date"


class CreatePermohonan(forms.ModelForm):
    class Meta:
        model = models.Permohonan
        fields = "__all__"
        exclude = ['uang_terpenuhi', 'urgency', 'comments', 'semua_pemberian', 'tanggal_pembuatan']

        widgets = {
            "deadline": DateInput
        }

# class SearchPermohonan(forms.Form):
#     searched = forms.CharField(max_length=100)

Comments/views.py
from django.shortcuts import render

# Create your views here.

Donatsi/views.py
from django.shortcuts import render, redirect
from PermohonanDonasi.models import Permohonan
# from PermohonanDonasi.forms import SearchPermohonan

# Create your views here.
def homepage(request):
    recommendations = []
    for i in range(5,0,-1):
        permohonan_query = Permohonan.objects.filter(urgency = i)
        for permohonan in permohonan_query:
            if(len(recommendations) < 6):
                recommendations.append(permohonan)
            else:
                break
        if(len(recommendations) >= 6):
            break

    return render(request,"homepage.html", {"recommendations": recommendations})

def about(request):
    return render(request, "about.html")

KategoriDonasi/views.py
from django.shortcuts import render

# Create your views here.

PemberianDonasi/views.py
from django.shortcuts import render, redirect
from PermohonanDonasi.models import Permohonan
from .forms import CreatePemberian

# Create your views here.
def daftar_pemberian(request, id):
    if(request.method == "POST"):
        form = CreatePemberian(request.POST)
        if form.is_valid():
            pemberian = form.save(commit=False)
            donasi = Permohonan.objects.get(id=id)
            donasi.uang_terpenuhi += pemberian.jumlah_uang
            donasi.save()
            pemberian.donasi = donasi
            pemberian.save()
            return redirect("permohonan:detail-permohonan", id=donasi.id)
    
    form = CreatePemberian()
    return render(request, "daftar-pemberian.html", {"form": form})

PermohonanDonasi/views.py
from django.shortcuts import render, redirect
from .forms import CreatePermohonan
from KategoriDonasi.models import Kategori
from .models import Permohonan

# Create your views here.
def daftar_permohonan(request):
    form = CreatePermohonan()
    if request.method == "POST":
        form = CreatePermohonan(request.POST, request.FILES)
        if form.is_valid():
            permohonan = form.save(commit=False)
            permohonan.urgency = permohonan.kategori_alasan.urgency    
            permohonan.save()
            return redirect("homepage")
    return render(request, "daftar-permohonan.html", {'form': form})

def list_permohonan(request):
    query = request.GET.get("query")
    if query:
        objects = Permohonan.objects.filter(nama_donasi__contains=query)
    else:
        objects = Permohonan.objects.all()
    return render(request, 'semua-permohonan.html', {"objects": objects})

def detail_permohonan(request, id):
    permohonan = Permohonan.objects.get(id=id)
    return render(request, 'detail-permohonan.html', {"permohonan": permohonan})

PemberianDonasi/templates/daftar-pemberian.html
{% extends 'base-template.html' %}

{% block content %}
<form method="post" action="">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="donasi">
</form>
{% endblock %}

PermohonanDonasi/templates/daftar-permohonan.html
{% extends 'base-template.html' %}

{% block content %}
    <form class="form-daftar" action="" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <div class="form-baris">
                <div class="form-field">
                    <p>JUDUL DONASI</p>
                    <p> {{ form.nama_donasi }} </p>
                </div>
                <div class="form-field">
                    <p>TIPE DONASI</p>
                    <p>{{ form.kategori_alasan }}</p>
                </div>
        </div>
        <div class="form-baris">
            <div class="form-field">
                <p>NAMA PEMOHON</p>
                <p>{{ form.nama_pemohon }}</p>
            </div>
            <div class="form-field">
                <p>EMAIL PEMOHON</p>
                <p>{{ form.email }}</p>
            </div>
        </div>
        <div class="form-baris">
            <div class="form-field">
                <p>NO TELP PEMOHON</p>
                <p>{{ form.nomor_telp }}</p>
            </div>
            <div class="form-field">
                <p>JUMLAH DONASI (Rp)</p>
                <p>{{ form.target_uang }}</p>
            </div>
        </div>
        <div class="form-baris">
            <div class="form-field">
                <p>BANK PEMOHON</p>
                <p>{{ form.bank }}</p>
            </div>
            <div class="form-field">
                <p>NOMOR REKENING</p>
                <p>{{ form.rekening }}</p>
            </div>
        </div>
        <div class="form-baris">
            <div class="form-field">
                <p>DESKRIPSI DONASI</p>
                <p>{{ form.deskripsi_alasan }}</p>
            </div>
        </div>
        <div class="form-baris">
            <div class="form-field">
                <p>DEADLINE</p>
                <p>{{ form.deadline }}</p>
            </div>
            <div class="form-field">
                <p>FOTO</p>
                <p>{{ form.image_donasi }}</p>
            </div>
        </div>

        <input type="submit" value="Submit">
    </form>
{% endblock %}

PermohonanDonasi/templates/detail-permohonan.html
{% extends 'base-template.html' %}

{% block content %}
<h1>{{ permohonan.nama_donasi }}</h1>
<img src="{{ permohonan.image_donasi.url }}" alt="image">
<div class="pemohon-deskripsi">
    <div class="pemohon-detail">
        <p>Nama pemohon: {{ permohonan.nama_pemohon }}</p>
        <p>Email: {{ permohonan.email }}</p>
        <p>Nomor telp: {{ permohonan.email }}</p>
    </div>
    <div class="deskripsi">
        <p>{{ permohonan.deskripsi_alasan }}</p>
        <p> 
            Rp. {{ permohonan.uang_terpenuhi }} / Rp. {{ permohonan.target_uang }}
        </p>
        <p>
            Deadline: {{ permohonan.deadline }}
        </p>
    </div>
</div>
{% endblock %}

PermohonanDonasi/templates/semua-permohonan.html
{% extends 'base-template.html' %}

{% block content %}
<form method="GET" action="{% url 'permohonan:list-permohonan' %}">
    <input type="text" name="query" placeholder="cari donasi...">
    <input type="submit" value="Search">
</form>

{% for permohonan in objects %}
<div class="permohonan">
    <img src="{{ permohonan.image_donasi.url }}" alt="image">
    <h1>
        {{ permohonan.nama_donasi }}
    </h1>
    <p>
        Kategori: {{ permohonan.kategori_alasan }}
    </p>
    <p>
        Deskripsi: {{ permohonan.deskripsi_singkat }}
    </p>
    <p> 
        Rp. {{ permohonan.uang_terpenuhi }} / Rp. {{ permohonan.target_uang }}
    </p>
    <p>
        Deadline: {{ permohonan.deadline }}
    </p>
    <a href="{% url 'pemberian:daftar_pemberian' id=permohonan.id %}"><button>Donate</button></a>
    <a href="{% url 'permohonan:detail-permohonan' id=permohonan.id %}"><p class="permohonan-details">Details</p></a>
</div>
{% endfor %}
{% endblock %}

templates/about.html
{% extends 'base-template.html' %}
{% block content %}
<p>About us</p>
{% endblock %}

templates/base-template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static  'base.css' %}">
    <link rel="stylesheet" href="{% static  'homepage.css' %}">
    <link rel="stylesheet" href="{% static  'daftar-permohonan.css' %}">
    <link rel="stylesheet" href="{% static  'list-permohonan.css' %}">
    <title>Donatsi</title>
</head>
<body>
    <nav>
    <div>
        <a href="{% url 'homepage' %}"><p>RECOMMENDATIONS</p></a>
        <a href="{% url 'about' %}"><p>TENTANG KAMI</p></a>
        <a href="{% url 'permohonan:list-permohonan' %}"><p>LIHAT DONASI</p></a>
        <a href="{% url 'permohonan:daftar-permohonan' %}"><p>BUKA DONASI</p></a>
    </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/homepage.html
{% extends 'base-template.html' %}
{% block content %}
<h1>HELLO THERE DONATors</h1>
<p>ini homepage</p>
<form method="GET" action="{% url 'permohonan:list-permohonan' %}">
    <input type="text" name="query" placeholder="cari donasi...">
    <input type="submit" value="Search">
</form>
{% if recommendations %}
<div class="recommendations">
    {% for permohonan in recommendations %}
    <div class="recommendation">
        <img src="{{ permohonan.image_donasi.url }}" alt="image">
        <h1>
            {{ permohonan.nama_donasi }}
        </h1>
        <p>
            Kategori: {{ permohonan.kategori_alasan }}
        </p>
        <p>
            Deskripsi: {{ permohonan.deskripsi_singkat }}
        </p>
        <p> 
            Rp. {{ permohonan.uang_terpenuhi }} / Rp. {{ permohonan.target_uang }}
        </p>
        <p>
            Deadline: {{ permohonan.deadline }}
        </p>

        <a href="{% url 'pemberian:daftar_pemberian' id=permohonan.id %}"><button>Donate</button></a>
        <a href="{% url 'permohonan:detail-permohonan' id=permohonan.id %}"><p class="permohonan-details">Details</p></a>

    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}